#!/usr/bin/env bash
# sassmany
function help {
    echo "sassmany - takes many args and runs sassit on them"
    echo "arguments should be filenames in dir without their extensions"
    echo "A folder called css_out will be the home of all generated css and maps"
    echo "normal, minified and fully commented versions are created in this file"
    echo "output filenames will match sources (todo: have _ append removed)"
    echo "extensions will be .min.css .css and -full.css"
}
while [ ! $# -eq 0 ]
do
    case "$1" in
        --help | -h | -help)
            help;
            exit 1
            ;;
    esac
done

mkdir -p css_out;

for VAR in "$@"; do
    sassit $VAR;
done