#!/usr/bin/env bash
######--------------------------------------------######
######  By Jeff Russ https://github.com/Jeff-Russ ######
######--------------------------------------------######
# s3rbf

if (( $# == 0 )); then 
  echo ""
  echo "s3rbf stands for Amazon 's3 remove bucket (with) force'"
  echo "s3rbf will remove a bucket and all of it's contents!"
  echo "useage: s3mb bucket-name"
  echo ""
else
   echo
   read -r -p "THIS WILL REMOVE BUCKET AND ALL CONTENTS! Proceed?? [Y/n]" response
   response=${response,,} # tolower
   echo
   if [[ $response =~ ^(yes|y| ) ]]; then
      aws s3 rb s3://$1 --force
   fi
fi