# b is for bash
alias brc='source ~/.bashrc'                          # bash rc: load ~/.bashrc 
alias bex='chmod u+x'                                 # (make it) bash executable

# p is for print (using cat)
alias pba='cat ~/bash_scripts/resources/bash_aliases' # look at bash aliases
alias pbr='cat ~/.bashrc'                             # look at bash resources
alias pbs='cat ~/bash_scripts/scripts *'              # look at bash scripts

# c9 is for the Cloud9 Ace editor
alias c9ba='c9 ~/bash_scripts/resources/bash_aliases' # edit aliases

# g is for git;  
alias gmv='git mv'                                  # gmv git mv
alias ga='git add . -A; git status'                 # ga  git add;  
alias gac='git add . -A; git status; git commit -m' # gac git add commit;
alias gcm='git commit --allow-empty -m'             # gcm git commit message
alias gc='git checkout'                             # gc  git checkout;  
alias gs='git status'                               # gs  git status;  
alias gu='git checkout --force; git status'         # gu  git undo
alias gm='git merge'                                # gm  git merge;  
alias gb='git branch'                               # gb  git branch;
alias gpo='git push origin'                         # gpo git push origin;

# r is for ruby or rails;  
alias rbu='bundle update'                           # rbu rails: bundle update;  
alias rbi='bundle install'                          # rbi rails: bundle install;  
alias rui='bundle update; bundle install'           # rui rails: update, install;
alias be='bundle exec'                              # be bundle exec
alias rg='bundle exec rails generate'               # rg  rails generate; 
alias rgc='bundle exec rails generate controller'   # rg  rails generate controller; 
alias rgm='bundle exec rails generate model'        # rgm rails generate MODEL????;
alias rd='bundle exec rails destroy'                # rd  rails db destroy;
alias rdr='bundle exec rake db:reset'               # rr  rake db reset;
alias rdm='bundle exec rake db:migrate'             # rr rake migrate; 
alias rc='bundle exec rails console'                # rc  rails console;  
alias rhc='heroku run rails console'                # rhc rails heroku console;    
alias rs='bundle exec rails server  -p $PORT -b $IP'             # rs  rails server;  
alias rd='git push heroku master; heroku run rake db:migrate'    # rd  rails: deploy;

# n is for navigate;  
alias nr='cd /; ls -a'                           # nr  navigate: root;  
alias nh='cd ~/; ls -a'                          # nh  navigate: home;  
alias nw='cd ~/workspace; ls -a'                 # nw  navigate: workspace;  
alias nbs='cd ~/bash_scripts; ls -a'             # nbs navigate: bash_scripts; 
alias ns='cd ~/bash_scripts/scripts; ls -a'      # ns navigate: bash_scripts/scripts/; 

# re is for rails edit (this only makes sense if you use c9.io);
alias rec='c9 app/controllers'
alias rev='c9 app/views/'
alias reg='c9 Gemfile'
alias rer='c9 config/routes.rb'
alias rem='c9 db/migrate/'
alias res='c9 db/schema.rb'

# Here are some more various mixed function aliases




