#!/bin/bash
# allremotes
# credit to https://coderwall.com/p/0ypmka/git-clone-all-remote-branches-locally

# run without arg in the git project root directory and it will add local tracking 
# of all branches on all remotes.

for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master `; do
   git branch --track ${branch#remotes/origin/} $branch
done