#!/bin/bash
# gacp git add commit push (with message)

branch=`git rev-parse --abbrev-ref HEAD`
   
if (( $# == 0 )); then 
   echo "This will add all 'git add . -A', commit and push to $branch"
   while true; do
      echo "Enter commit message in quotes or ctrl-c to cancel:"
      echo; read msg; echo
      echo "you entered $msg."
      read -p "To push to $branch enter 'y' to enter a different message, enter 'n'" yn
      case $yn in
         [Yy]* ) 
            git add . -A; 
            git status; 
            git commit -m "$msg"; 
            git push origin $branch;
            break;;
         [Nn]* ) continue;;
         * ) echo "Please answer yes or no.";;
      esac
   done
else
   git add . -A; 
   git status; 
   git commit -m "$1"; 
   git push origin $branch;
fi