#!/bin/bash
# add boostrap to rails app

# THIS FILE IS NOT COMPLETE

if grep -q 'bootstrap-sass' 'Gemfile'; then
	echo "bootstrap-sass found in Gemfile"
else
	sed -i '14 a 'gem "bootstrap-sass"'                   # Use bootstrap library for styles' Gemfile
fi